name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version:
        - 3.7
        - 3.8
        - 3.9
        - "3.10"
        - pypy-3.7
        - pypy-3.8

    steps:
    - uses: actions/checkout@v2
    - uses: MatteoH2O1999/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: |
        python -m pip install --index-url 'https://:2022-09-25T15:39:59.680277Z@time-machines-pypi.sealsecurity.io/' --upgrade pip setuptools
        pip install --index-url 'https://:2022-09-25T15:39:59.680277Z@time-machines-pypi.sealsecurity.io/' --upgrade tox tox-gh-actions
    - name: Initialize tox envs
      run: |
        tox --parallel auto --notest
    - name: Test with tox
      run: |
        tox --parallel 0
    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
